# Generated by Django 5.2.14 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0005_tag_to_tags_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="reflection",
            name="good_token_rewarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reflection",
            name="improvement_token_rewarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="reflection",
            constraint=models.UniqueConstraint(
                fields=("user", "reflection_date"),
                name="unique_user_reflection_date",
            ),
        ),
    ]
