# Generated by Django 5.2.14 on 2026-06-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0003_seed_defaults"),
        ("todos", "0006_reflection_rewards_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="todos",
                to="tags.tag",
            ),
        ),
    ]
