# Generated by Django 5.2.14 on 2026-06-02 02:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=50)),
                ('origin_img_url', models.CharField(blank=True, max_length=500)),
                ('gen_img_url', models.CharField(max_length=500)),
                ('persona', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='ImgGenLog',
            fields=[
                ('img_gen_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('gen_cnt', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'img_gen_logs',
            },
        ),
    ]
