# Generated by Django 5.2.14 on 2026-06-08 05:18

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterGenerationJob",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("personality_keywords", models.JSONField(default=list)),
                ("custom_prompt", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("in_progress", "in_progress"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("consumed", "consumed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("gen_img_object_key", models.CharField(blank=True, max_length=500)),
                ("gen_img_url", models.CharField(blank=True, max_length=500)),
                ("persona", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "character_generation_jobs",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="generation_job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="character",
                to="characters.charactergenerationjob",
            ),
        ),
        migrations.CreateModel(
            name="SourceImage",
            fields=[
                (
                    "source_img_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_key", models.CharField(max_length=500)),
                ("content_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_upload", "pending_upload"),
                            ("upload_completed", "upload_completed"),
                            ("upload_expired", "upload_expired"),
                        ],
                        default="pending_upload",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "source_images",
            },
        ),
        migrations.AddField(
            model_name="charactergenerationjob",
            name="source_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_jobs",
                to="characters.sourceimage",
            ),
        ),
    ]
