# Generated by Django 5.2.14 on 2026-06-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0003_charactergenerationjob_character_generation_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="character_name",
            field=models.CharField(max_length=8),
        ),
    ]
