# Generated by Django 5.2.14 on 2026-06-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0004_alter_character_character_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactergenerationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("IN_PROGRESS", "In Progress"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("CONSUMED", "Consumed"),
                ],
                default="QUEUED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourceimage",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_UPLOAD", "Pending Upload"),
                    ("UPLOAD_COMPLETED", "Upload Completed"),
                    ("UPLOAD_EXPIRED", "Upload Expired"),
                ],
                default="PENDING_UPLOAD",
                max_length=20,
            ),
        ),
    ]
