# Generated by Django 5.2.14 on 2026-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0005_status_values_uppercase"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="visual",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
