# Generated by Django 5.2.14 on 2026-06-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0006_character_visual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="gen_img_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="character",
            name="origin_img_url",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="charactergenerationjob",
            name="gen_img_url",
            field=models.TextField(blank=True),
        ),
    ]
