# Generated by Django 5.2.14 on 2026-06-16 08:48

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0007_alter_character_gen_img_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterHome",
            fields=[
                (
                    "house_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exterior_type", models.CharField(max_length=30)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "db_table": "character_homes",
            },
        ),
    ]
