# Generated by Django 5.2.14 on 2026-06-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0007_alter_character_gen_img_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactergenerationjob",
            name="appearance",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
