# Generated by Django 5.2.14 on 2026-06-17 01:30

from typing import Any

from django.db import migrations, models


def rename_exterior_types(apps: Any, schema_editor: Any) -> None:
    CharacterHome = apps.get_model("characters", "CharacterHome")
    mapping = {
        "house_yellow": "yellow",
        "house_blue": "blue",
        "house_green": "green",
        "house_purple": "purple",
    }
    for old, new in mapping.items():
        CharacterHome.objects.filter(exterior_type=old).update(exterior_type=new)


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0008_characterhome"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterhome",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="characterhome",
            name="exterior_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="characterhome",
            name="position_x",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="characterhome",
            name="position_y",
            field=models.FloatField(default=0.0),
        ),
        migrations.RunPython(rename_exterior_types, migrations.RunPython.noop),
    ]
