# Generated by Django 5.2.14 on 2026-06-17 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0008_charactergenerationjob_appearance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactergenerationjob",
            name="error_code",
        ),
        migrations.RemoveField(
            model_name="charactergenerationjob",
            name="error_message",
        ),
    ]
