# Generated by Django 5.2.14 on 2026-06-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0012_remove_character_gen_img_object_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactergenerationjob",
            name="img_gen_log_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
