# Generated by Django 5.2.14 on 2026-06-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_notification_tokentransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="token_hash",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
