# Generated by Django 5.2.14 on 2026-06-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_refreshtoken_token_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtoken",
            name="persistent",
            field=models.BooleanField(default=True),
        ),
    ]
