# Generated by Django 5.2.14 on 2026-06-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_refreshtoken_persistent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.DateField(),
        ),
    ]
