# Generated by Django 5.2.14 on 2026-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="personalization",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
