# Generated by Django 5.2.14 on 2026-06-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_notification_data"),
        ("users", "0006_user_personalization"),
    ]

    operations = []
