# Generated by Django 5.2.14 on 2026-06-02 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quests", "0001_initial"),
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="todo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quests",
                to="todos.todo",
            ),
        ),
    ]
