# Generated by Django 5.2.14 on 2026-06-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="character_reaction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quest",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("COMPLETED", "COMPLETED"),
                    ("FAILED", "FAILED"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
