# Generated by Django 5.2.14 on 2026-06-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
