# Generated by Django 5.2.14 on 2026-06-24 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ("created_at",)},
        ),
    ]
